### ISSUE TITLE
Allow EC keys

### ISSUE THREAD

**Issue by cagriemer** [veeti/manuale#13]
Hi there, thanks for this great project.

At the moment, **manuale** does not officially support the use of EC keys. I know it is not optimal (mostly due to the function names) but just by commenting out 4 lines in crypto.py file, it is possible to use the client with the EC keys in addition to the RSA keys. Here is the part that needs to be commented out (crypto.py file lines 94-97):

``` python
    if not isinstance(key, RSAPrivateKey):
        raise ValueError("Key is not a private RSA key.")
    elif key.key_size < 2048:
        raise ValueError("The key must be 2048 bits or longer.")
```

I thought this little workaround might be useful for people who need EC certificates and wanted to share in an issue instead of sending a pull request.

Thanks again for providing a let's encrypt client with a sane user interface.

**Comment by veeti** [comment]
Thanks! I added in support for providing EC keys. Some day I'll get around to adding full support.
