### ISSUE TITLE
How to renew authorisation?

### ISSUE THREAD

**Issue by pcolmer** [veeti/manuale#16]
Hi

Apologies if I'm about to ask something that is more down to how Let's Encrypt works ...

I've just started trying your tool. I've authorised a domain and the completion has said "Authorization lasts until 2016-11-20T19:13:05Z". What isn't clear is what do I do in order to "renew" that authorisation?

If I just run "manuale authorize <domain>", will that give me a fresh TXT record that I've got to plug into the DNS or will it extend the authorisation of the domain now that it has been authorised?

I'm trying to understand how renewal in general (authorisation and certificate) works with your tool.

Thanks.

**Comment by veeti** [comment]
There is no technical distinction between creating a new authorization and "renewing" one: to renew, you create a new authorization for the domain (which will have a new TXT record to set). The same goes for certificates: "renewing" is no different from issuing a new certificate for the same domain(s).

**Comment by pcolmer** [comment]
Thanks for the clarification.
