### ISSUE TITLE
Cert naming

### ISSUE THREAD

**Issue by szepeviktor** [veeti/manuale#18]
Thank you for your _simple_ client.
I helped me how the acme protocol works.

Would it be possible to provide templates for cert names? `%s-public.pem`
https://github.com/veeti/manuale/blob/master/manuale/issue.py#L78-L81

**Comment by szepeviktor** [comment]
I think the _simple_ solution is to rename them afterwards.

**Comment by veeti** [comment]
Sorry, not entirely sure what you mean. Do you mean changing the output filenames from the command line, or something else?

**Comment by szepeviktor** [comment]
> Do you mean changing the output filenames

Yes. I mean it.

**Comment by veeti** [comment]
I'm not against the idea. What sort of switch would you like in particular? Can you give me an example?

**Comment by szepeviktor** [comment]
```
--chain-template "combined-%s.pem" --certificate-template "pub-key-%s.pem" --intermediate-template "intermediate-%s.crt" --privatekey-template "priv-key-%s.key"
```

**Comment by szepeviktor** [comment]
Meanwhile I've got used to your naming :)
