### ISSUE TITLE
ECC certs support

### ISSUE THREAD

**Issue by hlx98007** [veeti/manuale#21]
Hi, does ManuaLE support ECC certs?

If so, how to apply?

Thanks.

**Comment by veeti** [comment]
There is no direct support for generating EC keys yet, but you can manually create a key using `openssl`/whatever and pass it to the `issue` command using `--key-file`.

**Comment by hlx98007** [comment]
Thanks for the info!

**Comment by szepeviktor** [comment]
See https://github.com/veeti/manuale/commit/99c986577dfd61e5cd30ce2501e9a78e094310d5

## 

+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
