### ISSUE TITLE
"issue" usage is incorrect

### ISSUE THREAD

**Issue by syrkuit** [veeti/manuale#29]
usage: manuale issue [-h] [--key-size KEY_SIZE] [--key-file KEY_FILE]
                     [--csr-file CSR_FILE] [--output OUTPUT]
                     domain [domain ...]

it implies it's possible to specify multiple domains, but only one domain is ever processed.

**Comment by szepeviktor** [comment]
Actually a LE certificate may include multiple domains.

**Comment by syrkuit** [comment]
yeah, just realized this.

**Comment by veeti** [comment]
All domains are in the certificate's SAN. The first domain is always used as the CN.
