### ISSUE TITLE
random certs deauthorzied and can not be renewed

### ISSUE THREAD

**Issue by yura-shutkin** [veeti/manuale#30]
Good day.
I do have right now 48 certs. They renewed at different dates, so I have max 19 renew in a week. But yesterday 18 of them did not renew with error:
```
Generating a 2048 bit RSA key. This might take a second.
Key generated.

Requesting certificate issuance...
Connection or service request failed. Aborting.
Error creating new cert :: authorizations for these names not found or expired: mysite.com (type urn:acme:error:unauthorized, HTTP 403)
```

How can I determine why it happened ? Or can you help me, or can I help you.
All certs issued max 2 months ago and some of them in use about half year (of course with renewing every 2 months)

**Comment by yura-shutkin** [comment]
Some of certs has dns records, and some not. Can't really say what's the difference between them (certs).

**Comment by szepeviktor** [comment]
I do these on renew:
```bash
manuale info
manuale authorize # -- Just to make sure it is authorized
manuale issue
openssl verify
```
https://github.com/szepeviktor/debian-server-tools/blob/master/security/cert-update-manuale-CN.sh#L30-L63

**Comment by szepeviktor** [comment]
Try asking your question on the forum
https://community.letsencrypt.org/

**Comment by yura-shutkin** [comment]
About renew. Yes, of course, I can't imagine another way for renewing. Thank you for a link, I'll ask on the community page.

**Comment by veeti** [comment]
You need to reauthorize the domains periodically. The authorize command prints the expiration date for each authorization.

**Comment by yura-shutkin** [comment]
@veeti Is it possible prolong authorization without changing DNS record ?

GoDaddy, as I do know, has no API for changing DNS records.

**Comment by veeti** [comment]
No, sorry.

**Comment by szepeviktor** [comment]
Yes, this issue is not the appropriate place for that.
Although you may take a look at `PATCH /v1/domains/{domain}/records`
https://developer.godaddy.com/doc
And you may know that the authorization record could be deleted right away.

**Comment by yura-shutkin** [comment]
Thank you very much @szepeviktor.
API did not worked for me cause test token. With production it works. Seems I'll update my script so after fail on renew will be authorization. Don't know how I'll proceed press enter, but I think this is not impossible choice.

**Comment by szepeviktor** [comment]
> Don't know how I'll proceed

Please note the project's **name**!

**Comment by yura-shutkin** [comment]
It's internal company's automation. But it's possible. I will be glad to write your project's name

**Comment by szepeviktor** [comment]
This project's name is **manuale**
meaning *A fully manual Let's Encrypt/ACME client*

**Comment by yura-shutkin** [comment]
Manuale allready added to README.md

About my automation:
All I did is add few scripts on bash which uses your application (Manuale) for renewing and applying new certs

**Comment by veeti** [comment]
You would be better off using a client designed for use in automatic scripts. For example, [acme.sh](https://github.com/Neilpang/acme.sh) has integration with GoDaddy DNS. You can find a full list of clients [here](https://community.letsencrypt.org/t/list-of-client-implementations/2103).

**Comment by yura-shutkin** [comment]
Thank you, I'll look on it. But we do use not only godaddy's servers, linode also.
